s(:iter,
 s(:call,
  s(:colon2, s(:const, :ActiveRecord), :Schema),
  :define,
  s(:hash, s(:lit, :version), s(:lit, 1))),
 s(:args),
 s(:block,
  s(:iter,
   s(:call,
    nil,
    :create_table,
    s(:str, "activities"),
    s(:hash, s(:lit, :force), s(:true))),
   s(:args, :t),
   s(:block,
    s(:call, s(:lvar, :t), :string, s(:str, "name")),
    s(:call, s(:lvar, :t), :datetime, s(:str, "start_time")),
    s(:call, s(:lvar, :t), :datetime, s(:str, "created_at")),
    s(:call, s(:lvar, :t), :datetime, s(:str, "updated_at")))),
  s(:iter,
   s(:call,
    nil,
    :create_table,
    s(:str, "shape"),
    s(:hash, s(:lit, :force), s(:true))),
   s(:args, :t),
   s(:block,
    s(:call, s(:lvar, :t), :integer, s(:str, "customer_id")),
    s(:call, s(:lvar, :t), :integer, s(:str, "size")),
    s(:call, s(:lvar, :t), :integer, s(:str, "width")),
    s(:call, s(:lvar, :t), :integer, s(:str, "height")),
    s(:call, s(:lvar, :t), :datetime, s(:str, "created_at")),
    s(:call, s(:lvar, :t), :datetime, s(:str, "updated_at"))))))
